/**
 * The synthesis knowledge base — a compact reference injected into the single
 * Harness synthesis pass so it generates a GOOD, enforceable harness rather than
 * generic boilerplate. Distilled from the proven two-layer harness shipped in the
 * boringstack + shiroani repos: a custom ESLint plugin for architecture-level AST
 * rules, plus a separate `lint-meta` engine for everything ESLint can't reach, plus
 * an agent-read-first contract doc. Kept short (it is prompt context, not code).
 */
export const HARNESS_REFERENCE: string = [
  'HARNESS REFERENCE — the proven patterns for an enforceable codebase harness.',
  '',
  'TWO LAYERS. A good harness is two complementary enforcement layers:',
  '',
  '1) A CUSTOM ESLINT PLUGIN — AST rules that enforce ARCHITECTURE, not style.',
  '   ESLint/Prettier already own formatting; the plugin owns structure. Good rules:',
  '   - folder-per-component: each component lives in its own folder with its',
  '     index/styles/tests; no loose sibling component files.',
  '   - no-cross-feature-imports: a feature may not import another feature\'s',
  '     internals — only its public barrel (or not at all).',
  '   - layer/import boundaries: enforce the allowed dependency direction (e.g. ui',
  '     may import core, core may not import ui); forbid upward + sideways imports.',
  '   - resource-prefix naming: files/symbols of a kind share a required prefix or',
  '     suffix (e.g. `*.route.ts`, `use*` hooks, `*Schema` zod).',
  '   - tenancy / transaction safety: every tenant-scoped query carries the tenant',
  '     filter; multi-step writes run in a transaction.',
  '   Rules use AST selectors, are registered via ESLint FLAT config, and are',
  '   autofixable wherever the fix is mechanical.',
  '',
  '2) A "LINT-META" ENGINE — a separate TS rule engine for what ESLint CANNOT reach:',
  '   cross-file contracts, non-JS files (configs, markdown, CI yaml), and config',
  '   parity across a monorepo. Each rule implements:',
  '     interface IMetaRule {',
  '       id: string;',
  '       category: \'config\' | \'source-text\' | \'supply-chain\' | \'ci\' | \'testing\';',
  '       description: string;',
  '       ciCritical?: boolean;',
  '       run(ctx): IViolation[];',
  '     }',
  '     interface IViolation { file: string; rule: string; message: string }',
  '   A `registry.ts` exports `META_RULES: IMetaRule[]`, a CLI runs them and exits',
  '   non-zero on a `ciCritical` violation, and a generated `RULES.md` catalogs them.',
  '',
  'AGENT_CONTRACT. A per-app, agent-read-FIRST markdown doc (CLAUDE.md / AGENTS.md /',
  'AGENT_CONTRACT.md) that lists every guardrail, the file-suffix conventions, and the',
  'forbidden imports — in the imperative, so an agent applies them without rediscovery.',
  'A lint-meta rule enforces the doc stays 1:1 with package.json (contract parity): if',
  'a guardrail is dropped from the doc but still wired, CI fails.',
  '',
  'AI-FIRST SEVERITY PHILOSOPHY: "error or off, never warn." Agents iterate by reading',
  'CI failures; a warning is a silent miss an agent will not act on. Hard-DENY the',
  'escape hatches that let an agent dodge the type system: `any`, `as` casts, and',
  'non-null `!`. A rule that matters is an error; a rule that does not is removed.',
  '',
  'SCOPING. Only propose the plugin + lint-meta layers when there is a monorepo or an',
  'existing eslint setup to host them; for a small single package, a tight',
  'AGENT_CONTRACT plus a few flat-config rules is the right-sized harness. Reuse what',
  'already exists (an existing plugin, lint-meta dir, or agent doc) — extend it, do not',
  'duplicate it.',
].join('\n');
