//! The portable Structure-Lock export writer (portable lock PR 3, #134) — NEW and
//! SEPARATE from [`super::apply`], which stays frozen.
//!
//! It stages a portable-lock bundle under `.nightcore/export/portable-lock/` so a
//! target repo can enforce its Structure-Lock outside Nightcore (plain CI, no
//! account, no server): a `schemaVersion`-stamped copy of the live manifest, a
//! deterministic `nightcore-lock.yml` GitHub Actions workflow that invokes the
//! published `@noctcore/harness` runner, and a `README.md` with the ONE manual step
//! (copy the workflow into `.github/workflows/` yourself and commit it).
//!
//! ## Why this is not `apply.rs` and why the workflow is STAGED
//! `.github/workflows/` is a DENIED write sink in [`crate::infra::safe_join`] precisely
//! because a file there auto-runs on the next push — so a CI workflow is human-committed
//! by design, NEVER tool-placed. The exporter therefore writes the workflow to the
//! staging dir and the README tells the user to copy it into `.github/workflows/`
//! themselves. This keeps the "never auto-write a CI sink" invariant intact WITHOUT
//! touching or weakening `apply.rs`.
//!
//! ## Trust basis
//! Every byte written here is DETERMINISTIC Rust template output, never model output —
//! the same trust basis as `write_merge_manifest`'s Rust-built check entry
//! (`apply.rs`). Containment still matters (a scanned repo may ship a symlinked
//! `.nightcore`), so each destination resolves through the shared
//! [`crate::infra::safe_join`] (symlink-escape + canonical containment) BEFORE any
//! write, mirroring `write_merge_manifest`'s guard. Re-export overwrites ONLY the
//! staging dir (idempotent, reviewable via `git diff`) and never touches live
//! `.github/workflows/`.

use std::path::{Path, PathBuf};

use serde::Serialize;
// `ts-rs` is a dev-dependency; the codegen derive is gated to `cfg(test)`.
#[cfg(test)]
use ts_rs::TS;

use crate::infra::safe_join::safe_join;
use crate::store::harness_manifest::stamp_live_manifest;

/// The pinned `@noctcore/harness` runner version the exported CI workflow invokes.
/// Kept in lockstep with the `@noctcore/harness` version published by PR 4 (#134);
/// never `@latest` — a target's CI must be reproducible (spec §5) and a compromised
/// future publish must not silently reach already-scaffolded repos. PR 4 publishes
/// `0.1.0` and keeps this in sync.
pub const PORTABLE_LOCK_RUNNER_VERSION: &str = "0.1.0";

/// The staging bundle's project-relative directory. A CONTAINED, NON-execution-sink
/// path (NOT one of `safe_join`'s denied sinks): the workflow YAML is staged here for
/// the human to copy into `.github/workflows/` (a denied sink), never auto-written.
const EXPORT_DIR_REL: &str = ".nightcore/export/portable-lock";

/// The bundle basenames, written in this order under [`EXPORT_DIR_REL`].
const BUNDLE_FILES: [&str; 3] = ["harness.json", "nightcore-lock.yml", "README.md"];

/// The result of a portable-lock export — the staging path, the files written, the
/// workflow YAML (so the UI can offer a copy button), and the pinned runner version.
/// Rust-authored ts-rs boundary type (registered in `bindings/export.rs`); web-facing
/// only, so it derives `Serialize` (never deserialized back).
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(export, export_to = "PortableLockExport.ts"))]
pub struct PortableLockExport {
    /// Absolute path to the staging dir (`<project>/.nightcore/export/portable-lock`).
    pub staging_dir: String,
    /// The project-relative paths written (`harness.json`, `nightcore-lock.yml`,
    /// `README.md`), in write order.
    pub files_written: Vec<String>,
    /// The exact `nightcore-lock.yml` text — offered with a copy button so the user
    /// can drop it into `.github/workflows/` (the ONE manual step).
    pub workflow_yaml: String,
    /// The pinned runner version the workflow invokes
    /// ([`PORTABLE_LOCK_RUNNER_VERSION`]).
    pub runner_version: String,
}

/// The deterministic `nightcore-lock.yml` GitHub Actions workflow (spec §3.4). The
/// runner is invoked by its PUBLISHED name `@noctcore/harness` (the `@noctcore` org
/// PR 4 publishes to), pinned to [`PORTABLE_LOCK_RUNNER_VERSION`] — never `@latest`.
/// Action majors are pinned to non-deprecated versions (`reference_ci_node20_deprecation`):
/// `checkout` matches this repo's own workflows (`@v7`); `setup-node@v5` is the current
/// non-deprecated major (the repo itself uses `oven-sh/setup-bun`, so there is no
/// in-repo `setup-node` pin to match). Node 22 = the runner floor + the repo floor.
fn workflow_yaml() -> String {
    format!(
        "# Generated by Nightcore — portable Structure-Lock. Commit into .github/workflows/.\n\
name: structure-lock\n\
on: [push, pull_request]\n\
jobs:\n\
  structure-lock:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v7\n\
      - uses: actions/setup-node@v5\n\
        with: {{ node-version: '22' }}\n\
      # PINNED runner version (§5 supply-chain) — matches the runner published in PR 4.\n\
      - run: npx --yes @noctcore/harness@{version} check\n",
        version = PORTABLE_LOCK_RUNNER_VERSION
    )
}

/// The deterministic bundle `README.md`: what the bundle is, the ONE manual step, how
/// to run locally, and the honest downstream-owned caveat (spec §5).
fn readme_markdown() -> String {
    format!(
        "# Portable Structure-Lock\n\
\n\
This bundle lets your CI enforce this repo's Structure-Lock **without Nightcore** — no\n\
server, no account, no install beyond a single `npx` runner.\n\
\n\
## What's here\n\
\n\
- `harness.json` — a copy of `.nightcore/harness.json` (the checks + policy), stamped\n\
  with a `schemaVersion` so the runner can read it forward-compatibly.\n\
- `nightcore-lock.yml` — a ready-to-commit GitHub Actions workflow that runs\n\
  `npx @noctcore/harness@{version} check` on every push and pull request.\n\
\n\
## Install (ONE manual step)\n\
\n\
The workflow is **staged here, not auto-installed** — a CI workflow must be committed\n\
by a human, never placed by a tool. Copy it into your workflows directory and commit it:\n\
\n\
```sh\n\
mkdir -p .github/workflows\n\
cp .nightcore/export/portable-lock/nightcore-lock.yml .github/workflows/nightcore-lock.yml\n\
git add .github/workflows/nightcore-lock.yml .nightcore/harness.json\n\
git commit -m \"ci: enforce portable Structure-Lock\"\n\
```\n\
\n\
Once committed, the check reds the build on any Structure-Lock violation — governing\n\
teammates who never open Nightcore.\n\
\n\
## Run it locally\n\
\n\
```sh\n\
npx --yes @noctcore/harness@{version} check\n\
```\n\
\n\
## Note on trust\n\
\n\
The runner enforces **whatever is present** in this repo. It is NOT an integrity check:\n\
it does not verify that the committed rules match what Nightcore originally generated. If\n\
someone weakens a rule or deletes a check, the runner enforces the weakened set. The\n\
control against silent weakening is **PR review of the diff** — a re-export produces a\n\
reviewable `git diff`, not a silent overwrite.\n",
        version = PORTABLE_LOCK_RUNNER_VERSION
    )
}

/// Re-assert, in the instant BEFORE the write syscall, that `dest`'s parent still
/// canonicalizes to inside `root` and that the leaf is not a symlink. Mirrors
/// `apply.rs::revalidate_parent_contained` (kept LOCAL — `apply.rs` is frozen and its
/// helper is private) to narrow the mid-path-symlink-swap TOCTOU window that
/// [`safe_join`]'s lstat walk alone leaves open. The atomic temp+rename below also
/// REPLACES a destination symlink rather than following it.
fn revalidate_parent_contained(root: &Path, dest: &Path) -> Result<(), String> {
    let root_canon = root
        .canonicalize()
        .map_err(|e| format!("project root {} is not accessible: {e}", root.display()))?;
    let parent = dest
        .parent()
        .ok_or_else(|| "export path has no parent directory".to_string())?;
    let parent_canon = parent
        .canonicalize()
        .map_err(|e| format!("cannot resolve {} before write: {e}", parent.display()))?;
    if parent_canon != root_canon && !parent_canon.starts_with(&root_canon) {
        return Err(format!(
            "export parent resolved outside the project root just before write: {}",
            dest.display()
        ));
    }
    if let Ok(meta) = std::fs::symlink_metadata(dest) {
        if meta.file_type().is_symlink() {
            return Err(format!(
                "export target became a symlink before write (rejected): {}",
                dest.display()
            ));
        }
    }
    Ok(())
}

/// Write one staged bundle file, OVERWRITING any prior copy (re-export is idempotent
/// and reviewable via `git diff` — decision 4). Creates the staging dir, re-validates
/// containment immediately before the write, then writes atomically (temp + rename).
fn write_staged(root: &Path, dest: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
    }
    revalidate_parent_contained(root, dest)?;
    crate::store::write_atomic(dest, content.as_bytes())
        .map_err(|e| format!("failed to write {}: {e}", dest.display()))
}

/// Stage the portable-lock bundle for `project_path` and return its descriptor.
///
/// Order matters for containment: every bundle destination is resolved through
/// [`safe_join`] FIRST (rejecting a symlinked `.nightcore` escaping the root, mirroring
/// `write_merge_manifest`'s test), so a rejection short-circuits BEFORE the live-manifest
/// stamp or any bundle write can follow the symlink out of the repo. Then the live
/// `.nightcore/harness.json` is stamped with `schemaVersion` (additive, idempotent —
/// [`stamp_live_manifest`]) and its stamped text becomes the bundle's `harness.json`
/// copy. Finally the deterministic workflow + README are staged beside it.
pub(super) fn write_portable_lock(project_path: &str) -> Result<PortableLockExport, String> {
    let root = Path::new(project_path);

    // Containment gate FIRST: resolve every destination through the shared safe_join.
    // A symlinked `.nightcore` (escaping or in-root) is rejected here, before any write.
    let dests: Vec<(String, PathBuf)> = BUNDLE_FILES
        .iter()
        .map(|name| {
            let rel = format!("{EXPORT_DIR_REL}/{name}");
            safe_join(root, &rel).map(|dest| (rel, dest))
        })
        .collect::<Result<_, _>>()?;

    // Stamp the live manifest (additive, idempotent) and reuse its text as the bundle's
    // `harness.json`. This is the only place the export touches the live manifest.
    let manifest_json = stamp_live_manifest(project_path)?;
    let workflow = workflow_yaml();
    let readme = readme_markdown();

    let content_for = |name: &str| -> &str {
        match name {
            "harness.json" => manifest_json.as_str(),
            "nightcore-lock.yml" => workflow.as_str(),
            _ => readme.as_str(),
        }
    };

    let mut files_written = Vec::with_capacity(dests.len());
    let mut staging_dir: Option<PathBuf> = None;
    for (rel, dest) in &dests {
        let name = rel.rsplit('/').next().unwrap_or(rel.as_str());
        write_staged(root, dest, content_for(name))?;
        if staging_dir.is_none() {
            staging_dir = dest.parent().map(Path::to_path_buf);
        }
        files_written.push(rel.clone());
    }

    let staging = staging_dir.ok_or("could not resolve the export staging dir")?;
    Ok(PortableLockExport {
        staging_dir: staging.to_string_lossy().into_owned(),
        files_written,
        workflow_yaml: workflow,
        runner_version: PORTABLE_LOCK_RUNNER_VERSION.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use tempfile::TempDir;

    fn seed_manifest(tmp: &TempDir, content: &str) {
        let dir = tmp.path().join(".nightcore");
        std::fs::create_dir_all(&dir).expect("create .nightcore");
        std::fs::write(dir.join("harness.json"), content).expect("write manifest");
    }

    fn staging(tmp: &TempDir) -> PathBuf {
        tmp.path().join(".nightcore/export/portable-lock")
    }

    #[test]
    fn stages_the_bundle_with_a_stamped_manifest_copy() {
        // The bundle lands under `.nightcore/export/portable-lock/`; `harness.json` is a
        // `schemaVersion`-stamped copy of the live manifest that preserves its checks.
        let tmp = TempDir::new().unwrap();
        seed_manifest(
            &tmp,
            r#"{ "checks": [ { "name": "folder", "kind": "lint-plugin", "command": "npx eslint ." } ] }"#,
        );

        let out = write_portable_lock(&tmp.path().to_string_lossy()).unwrap();

        for name in BUNDLE_FILES {
            assert!(
                staging(&tmp).join(name).exists(),
                "expected staged file {name}"
            );
        }

        let manifest: Value = serde_json::from_str(
            &std::fs::read_to_string(staging(&tmp).join("harness.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(manifest["schemaVersion"], 1, "bundle manifest is stamped");
        assert_eq!(
            manifest["checks"][0]["name"], "folder",
            "the armed check travels in the bundle"
        );

        // The live manifest is stamped too (so a re-export is idempotent on it).
        let live: Value = serde_json::from_str(
            &std::fs::read_to_string(tmp.path().join(".nightcore/harness.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(live["schemaVersion"], 1);
        assert_eq!(live["checks"][0]["name"], "folder");

        // Result descriptor.
        assert_eq!(out.runner_version, "0.1.0");
        assert_eq!(out.files_written.len(), 3);
        assert!(out.staging_dir.ends_with(".nightcore/export/portable-lock"));
    }

    #[test]
    fn workflow_is_deterministic_and_pins_the_published_runner() {
        // The staged YAML is a deterministic template that names the PUBLISHED package
        // `@noctcore/harness` pinned to the runner version — never `@latest`.
        let tmp = TempDir::new().unwrap();
        let out = write_portable_lock(&tmp.path().to_string_lossy()).unwrap();

        let yaml = std::fs::read_to_string(staging(&tmp).join("nightcore-lock.yml")).unwrap();
        assert_eq!(yaml, out.workflow_yaml, "returned YAML == the staged file");
        assert!(yaml.contains("name: structure-lock"));
        assert!(
            yaml.contains("npx --yes @noctcore/harness@0.1.0 check"),
            "must invoke the PUBLISHED @noctcore/harness pinned to the runner version"
        );
        assert!(
            !yaml.contains("@latest") && !yaml.contains("@nightcore/harness"),
            "never @latest, never the internal @nightcore name"
        );
        // Non-deprecated action majors (reference_ci_node20_deprecation).
        assert!(yaml.contains("actions/checkout@v7"));
        assert!(yaml.contains("actions/setup-node@v5"));
        assert!(!yaml.contains("@v4"), "no deprecated Node-20 action pin");
    }

    #[test]
    fn never_writes_under_dot_github() {
        // The workflow is STAGED, never auto-written into the denied `.github/` sink.
        let tmp = TempDir::new().unwrap();
        write_portable_lock(&tmp.path().to_string_lossy()).unwrap();
        assert!(
            !tmp.path().join(".github").exists(),
            "the CI sink stays human-committed — the exporter never touches .github/"
        );
    }

    #[test]
    fn re_export_overwrites_the_staging_dir_idempotently() {
        // Re-export rewrites ONLY the staging dir, byte-identically (deterministic).
        let tmp = TempDir::new().unwrap();
        seed_manifest(
            &tmp,
            r#"{ "checks": [ { "name": "lint", "kind": "lint-plugin", "command": "npx eslint ." } ] }"#,
        );
        let first = write_portable_lock(&tmp.path().to_string_lossy()).unwrap();
        let yaml1 = std::fs::read_to_string(staging(&tmp).join("nightcore-lock.yml")).unwrap();
        let readme1 = std::fs::read_to_string(staging(&tmp).join("README.md")).unwrap();

        let second = write_portable_lock(&tmp.path().to_string_lossy()).unwrap();
        let yaml2 = std::fs::read_to_string(staging(&tmp).join("nightcore-lock.yml")).unwrap();
        let readme2 = std::fs::read_to_string(staging(&tmp).join("README.md")).unwrap();

        assert_eq!(yaml1, yaml2, "re-export is byte-identical");
        assert_eq!(readme1, readme2);
        assert_eq!(first.files_written, second.files_written);
    }

    #[test]
    fn exports_even_when_no_manifest_exists_yet() {
        // No armed checks: the export still produces a valid v1 bundle (the runner then
        // finds no checks ⇒ exit 0). It must not hard-fail.
        let tmp = TempDir::new().unwrap();
        let out = write_portable_lock(&tmp.path().to_string_lossy()).unwrap();
        let manifest: Value = serde_json::from_str(
            &std::fs::read_to_string(staging(&tmp).join("harness.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(manifest["schemaVersion"], 1);
        assert_eq!(out.files_written.len(), 3);
    }

    #[test]
    fn refuses_a_malformed_live_manifest() {
        // The stamp step errors on a malformed manifest (never reset it into the bundle),
        // and the broken file is preserved.
        let tmp = TempDir::new().unwrap();
        seed_manifest(&tmp, "{ not json");
        assert!(write_portable_lock(&tmp.path().to_string_lossy()).is_err());
        let raw = std::fs::read_to_string(tmp.path().join(".nightcore/harness.json")).unwrap();
        assert_eq!(raw, "{ not json", "the broken manifest is preserved");
    }

    #[cfg(unix)]
    #[test]
    fn rejects_a_symlinked_nightcore_escaping_the_root() {
        // Defence in depth, cloned from `write_merge_manifest_rejects_a_symlinked_manifest_
        // escaping_the_root` (apply.rs): a scanned repo shipping `.nightcore` as a symlink
        // to an outside dir must not let the export escape the project root — and the
        // containment gate must fire BEFORE the live-manifest stamp writes anything.
        let root = TempDir::new().unwrap();
        let outside = TempDir::new().unwrap();
        std::os::unix::fs::symlink(outside.path(), root.path().join(".nightcore")).unwrap();

        assert!(
            write_portable_lock(&root.path().to_string_lossy()).is_err(),
            "a symlinked .nightcore escaping the root must be rejected"
        );
        assert!(
            !outside.path().join("harness.json").exists(),
            "the live-manifest stamp must not follow the symlink out of the root"
        );
        assert!(
            !outside.path().join("export").exists(),
            "no bundle written outside the root"
        );
    }
}
